export const SET_TOPICSLIST = "SET_TOPICSLIST";
export const SET_NAME = "SET_NAME";
export const ADD_SELECTEDTOPICSLIST = "ADD_SELECTEDTOPICSLIST";
export const REMOVE_SELECTEDTOPICSLIST = "REMOVE_SELECTEDTOPICSLIST";
